FROM container-registry.oracle.com/java/jdk:25.0.4.1 AS builder
WORKDIR /opt/app

COPY ./target/layered-jar-spring-boot-*.jar app.jar
RUN java -Djarmode=tools -jar 'app.jar' extract --layers --destination 'extracted'

FROM container-registry.oracle.com/java/jdk:25.0.4.1
WORKDIR /opt/app

COPY --from=builder /opt/app/extracted/dependencies/          ./
COPY --from=builder /opt/app/extracted/spring-boot-loader/    ./
COPY --from=builder /opt/app/extracted/snapshot-dependencies/ ./
COPY --from=builder /opt/app/extracted/application/           ./

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
