FROM container-registry.oracle.com/java/jdk:25.0.4.1@sha256:947650420cbf1a8d0ade992ed0cdc2edab4f8d4da1b80f501a56d3392e09e921
WORKDIR /opt/app

# Use an arbitrary high numeric UID so the container does not run as root.
COPY --chown=10001:0 ./target/container-image-hygiene-spring-boot-*.jar app.jar
USER 10001:0

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
