FROM container-registry.oracle.com/java/jdk:25.0.4.1
WORKDIR /opt/app

ARG JAR_FILE=./target/java-command-line-options-spring-boot-1.0.0.jar

COPY ${JAR_FILE} app.jar

ENV JDK_JAVA_OPTIONS="-XshowSettings:vm"

ENTRYPOINT ["java", "-jar", "app.jar"]
