CREATE TABLE quote (
    id      INT AUTO_INCREMENT NOT NULL,
    author  VARCHAR(32) NOT NULL,
    quote   VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO quote (author, quote) VALUES
  ('Abraham Lincoln',              'Give me six hours to chop down a tree and I will spend the first four sharpening the axe.'),
  ('Abraham Lincoln',              'I am a slow walker, but I never walk back.'),
  ('Abraham Lincoln',              'Whatever you are, be a good one.'),
  ('Abraham Lincoln',              'You can fool all of the people some of the time, and some of the people all of the time, but you can’t fool all of the people all of the time.'),
  ('Aesop',                        'United we stand, divided we fall.'),
  ('Albert Einstein',              'A person who never made a mistake never tried anything new.'),
  ('Albert Einstein',              'Education is what remains after one has forgotten what one has learned in school.'),
  ('Albert Einstein',              'I have no special talent. I am only passionately curious.'),
  ('Albert Einstein',              'If you can’t explain it simply, you don’t understand it well enough.'),
  ('Albert Einstein',              'Imagination is more important than knowledge.'),
  ('Albert Einstein',              'In the middle of difficulty lies opportunity.'),
  ('Albert Einstein',              'Life is like riding a bicycle. To keep your balance, you must keep moving.'),
  ('Albert Einstein',              'The important thing is not to stop questioning. Curiosity has its own reason for existing.'),
  ('Albert Einstein',              'Try not to become a man of success, but rather try to become a man of value.'),
  ('Albert Einstein',              'Weakness of attitude becomes weakness of character.'),
  ('Alexander Pope',               'To err is human; to forgive, divine.'),
  ('Alfred Lord Tennyson',         'Hope smiles from the threshold of the year to come, whispering "it will be happier."'),
  ('Alfred Lord Tennyson',         'Tis better to have loved and lost than to have never loved at all.'),
  ('Aristotle',                    'Courage is the first of human qualities because it is the quality which guarantees the others.'),
  ('Aristotle',                    'Happiness depends upon ourselves.'),
  ('Aristotle',                    'It is the mark of an educated mind to be able to entertain a thought without accepting it.'),
  ('Aristotle',                    'Knowing yourself is the beginning of all wisdom.'),
  ('Aristotle',                    'Patience is bitter, but its fruit is sweet.'),
  ('Aristotle',                    'Pleasure in the job puts perfection in the work.'),
  ('Aristotle',                    'The energy of the mind is the essence of life.'),
  ('Aristotle',                    'The more you know, the more you realize you don’t know.'),
  ('Aristotle',                    'The whole is greater than the sum of its parts.'),
  ('Aristotle',                    'We are what we repeatedly do. Excellence, then, is not an act, but a habit.'),
  ('Benjamin Franklin',            'An investment in knowledge pays the best interest.'),
  ('Benjamin Franklin',            'By failing to prepare, you are preparing to fail.'),
  ('Benjamin Franklin',            'Diligence is the mother of good luck.'),
  ('Benjamin Franklin',            'Do not fear mistakes. You will know failure. Continue to reach out.'),
  ('Benjamin Franklin',            'Early to bed and early to rise makes a man healthy, wealthy, and wise.'),
  ('Benjamin Franklin',            'Energy and persistence conquer all things.'),
  ('Benjamin Franklin',            'Never leave that till tomorrow which you can do today.'),
  ('Benjamin Franklin',            'Nothing is certain except for death and taxes.'),
  ('Benjamin Franklin',            'Tell me and I forget. Teach me and I remember. Involve me and I learn.'),
  ('Benjamin Franklin',            'Three can keep a secret, if two of them are dead.'),
  ('Benjamin Franklin',            'To succeed, jump as quickly at opportunities as you do at conclusions.'),
  ('Benjamin Franklin',            'Well done is better than well said.'),
  ('Bickle (character)',           'You talkin’ to me?'),
  ('Buddha',                       'Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.'),
  ('Buddha',                       'The mind is everything. What you think you become.'),
  ('Captain (character)',          'What we’ve got here is failure to communicate. Some men you just can’t reach.'),
  ('Charles-Guillaume Étienne',    'If you want something done right, do it yourself.'),
  ('Confucius',                    'It does not matter how slowly you go as long as you do not stop.'),
  ('Confucius',                    'Our greatest glory is not in never falling, but in rising every time we fall.'),
  ('Dorothy (character)',          'I’ve got a feeling we’re not in Kansas anymore.'),
  ('Dorothy (character)',          'There’s no place like home.'),
  ('Eleanor Roosevelt',            'Do one thing every day that scares you.'),
  ('Eleanor Roosevelt',            'Great minds discuss ideas; average minds discuss events; small minds discuss people.'),
  ('Eleanor Roosevelt',            'Happiness is not a goal; it is a by-product.'),
  ('Eleanor Roosevelt',            'If life were predictable it would cease to be life, and be without flavor.'),
  ('Eleanor Roosevelt',            'It is better to light a candle than curse the darkness.'),
  ('Eleanor Roosevelt',            'Life is what you make it. Always has been, always will be.'),
  ('Eleanor Roosevelt',            'No one can make you feel inferior without your consent.'),
  ('Eleanor Roosevelt',            'People grow through experience if they meet life honestly and courageously. This is how character is built.'),
  ('Eleanor Roosevelt',            'The future belongs to those who believe in the beauty of their dreams.'),
  ('Eleanor Roosevelt',            'With the new day comes new strength and new thoughts.'),
  ('Eleanor Roosevelt',            'You must do the things you think you cannot do.'),
  ('Epictetus',                    'No great thing is created suddenly, any more than a bunch of grapes or a fig.'),
  ('Forrest Gump (character)',     'Life is like a box of chocolates. You never know what you’re gonna get.'),
  ('Franklin D. Roosevelt',        'The only thing we have to fear is fear itself.'),
  ('Friedrich Nietzsche',          'That which does not kill us makes us stronger.'),
  ('George Bernard Shaw',          'Life isn’t about finding yourself. Life is about creating yourself.'),
  ('George Eliot',                 'It’s never too late to be what you might have been.'),
  ('Harry Callahan (character)',   'Go ahead, make my day.'),
  ('Henry David Thoreau',          'Go confidently in the direction of your dreams. Live the life you have imagined.'),
  ('Henry Ford',                   'Chop your own wood and it will warm you twice.'),
  ('Henry Ford',                   'Coming together is a beginning; keeping together is progress; working together is success.'),
  ('Henry Ford',                   'Don’t find fault, find a remedy; anybody can complain.'),
  ('Henry Ford',                   'Failure is simply the opportunity to begin again, this time more intelligently.'),
  ('Henry Ford',                   'If everyone is moving forward together, then success takes care of itself.'),
  ('Henry Ford',                   'Obstacles are those frightful things you see when you take your eyes off your goal.'),
  ('Henry Ford',                   'The only real mistake is the one from which we learn nothing.'),
  ('Henry Ford',                   'Vision without execution is just hallucination.'),
  ('Henry Ford',                   'Whether you think you can or you think you can’t, you’re right.'),
  ('Henry Ford',                   'You can’t build a reputation on what you are going to do.'),
  ('Isaac Newton',                 'A man may imagine things that are false, but he can only understand things that are true.'),
  ('Isaac Newton',                 'Errors are not in the art but in the artificers.'),
  ('Isaac Newton',                 'I can calculate the motion of heavenly bodies, but not the madness of people.'),
  ('Isaac Newton',                 'If I have seen further, it is by standing on the shoulders of giants.'),
  ('Isaac Newton',                 'If others would think as hard as I did, then they would get similar results.'),
  ('Isaac Newton',                 'Live your life as an Exclamation rather than an Explanation.'),
  ('Isaac Newton',                 'Tact is the art of making a point without making an enemy.'),
  ('Isaac Newton',                 'To every action there is always opposed an equal reaction.'),
  ('Isaac Newton',                 'Truth is ever to be found in simplicity, and not in the multiplicity and confusion of things.'),
  ('Isaac Newton',                 'What we know is a drop, what we don’t know is an ocean.'),
  ('J. R. R. Tolkien',             'All we have to decide is what to do with the time that is given us.'),
  ('J. R. R. Tolkien',             'Courage is found in unlikely places.'),
  ('J. R. R. Tolkien',             'Deeds will not be less valiant because they are unpraised.'),
  ('J. R. R. Tolkien',             'Even the smallest person can change the course of the future.'),
  ('J. R. R. Tolkien',             'Faithless is he that says farewell when the road darkens.'),
  ('J. R. R. Tolkien',             'I will not say: do not weep; for not all tears are an evil.'),
  ('J. R. R. Tolkien',             'It is useless to meet revenge with revenge; it will heal nothing.'),
  ('J. R. R. Tolkien',             'Not all those who wander are lost.'),
  ('J. R. R. Tolkien',             'The wide world is all about you: you can fence yourselves in, but you cannot forever fence it out.'),
  ('James Cameron',                'If you set your goals ridiculously high and it’s a failure, you will fail above everyone else’s success.'),
  ('Jean-Paul Sartre',             'Hell is other people.'),
  ('Jim Lovell (character)',       'Houston, we have a problem.'),
  ('John Dalberg-Acton',           'Power corrupts; absolute power corrupts absolutely.'),
  ('John F. Kennedy',              'Ask not what your country can do for you; ask what you can do for your country.'),
  ('John Lennon',                  'Life is what happens when you’re busy making other plans.'),
  ('Lao Tzu',                      'Mastering others is strength. Mastering yourself is true power.'),
  ('Lao Tzu',                      'The journey of a thousand miles begins with one step.'),
  ('Lao Tzu',                      'When I let go of what I am, I become what I might be.'),
  ('Mae West',                     'You only live once, but if you do it right, once is enough.'),
  ('Marcus Aurelius',              'The happiness of your life depends upon the quality of your thoughts.'),
  ('Margaret Thatcher',            'Being powerful is like being a lady. If you have to tell people you are, you aren’t.'),
  ('Margaret Thatcher',            'Disciplining yourself to do what you know is right and important, although difficult, is the highroad to pride, self-esteem, and personal satisfaction.'),
  ('Margaret Thatcher',            'Don’t follow the crowd, let the crowd follow you.'),
  ('Margaret Thatcher',            'If you want something said, ask a man; if you want something done, ask a woman.'),
  ('Margaret Thatcher',            'Plan your work for today and every day, then work your plan.'),
  ('Margaret Thatcher',            'There is no such thing as society: there are individual men and women, and there are families.'),
  ('Margaret Thatcher',            'Watch your thoughts, for they will become actions. Watch your actions, for they’ll become… habits. Watch your habits, for they will forge your character. Watch your character, for it will make your destiny.'),
  ('Margaret Thatcher',            'What is success? I think it is a mixture of having a flair for the thing that you are doing; knowing that it is not enough, that you have got to have hard work and a certain sense of purpose.'),
  ('Margaret Thatcher',            'You may have to fight a battle more than once to win it.'),
  ('Mark Twain',                   'A man who carries a cat by the tail learns something he can learn in no other way.'),
  ('Mark Twain',                   'Age is an issue of mind over matter. If you don’t mind, it doesn’t matter.'),
  ('Mark Twain',                   'Courage is resistance to fear, mastery of fear, not absence of fear.'),
  ('Mark Twain',                   'Good friends, good books, and a sleepy conscience: this is the ideal life.'),
  ('Mark Twain',                   'I have never let my schooling interfere with my education.'),
  ('Mark Twain',                   'It’s not the size of the dog in the fight, it’s the size of the fight in the dog.'),
  ('Mark Twain',                   'Kindness is the language which the deaf can hear and the blind can see.'),
  ('Mark Twain',                   'Never argue with stupid people, they will drag you down to their level and then beat you with experience.'),
  ('Mark Twain',                   'Patriotism is supporting your country all the time, and your government when it deserves it.'),
  ('Mark Twain',                   'The best way to cheer yourself up is to try to cheer somebody else up.'),
  ('Mark Twain',                   'The two most important days in your life are the day you are born and the day you find out why.'),
  ('Mark Twain',                   'To succeed in life, you need two things: ignorance and confidence.'),
  ('Mark Twain',                   'Whenever you find yourself on the side of the majority, it is time to pause and reflect.'),
  ('Mark Twain',                   'Wrinkles should merely indicate where smiles have been.'),
  ('Martin Luther King Jr.',       'I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character.'),
  ('Mahatma Gandhi',               'You must be the change you wish to see in the world.'),
  ('Michael Corleone (character)', 'Keep your friends close, but your enemies closer.'),
  ('Neil Armstrong',               'That’s one small step for a man, a giant leap for mankind.'),
  ('Nelson Mandela',               'The greatest glory in living lies not in never falling, but in rising every time we fall.'),
  ('Oprah Winfrey',                'If you look at what you have in life, you’ll always have more. If you look at what you don’t have in life, you’ll never have enough.'),
  ('Ralph Waldo Emerson',          'Self-trust is the first secret of success.'),
  ('Ralph Waldo Emerson',          'What lies behind us and what lies before us are tiny matters compared to what lies within us.'),
  ('René Descartes',               'I think therefore I am.'),
  ('Robert Frost',                 'Two roads diverged in a wood, and I, I took the one less travelled by, and that has made all the difference.'),
  ('Robert H. Schuller',           'Tough times never last but tough people do.'),
  ('Rudyard Kipling',              'He travels the fastest who travels alone.'),
  ('Sherlock Holmes (character)',  'Elementary, my dear Watson.'),
  ('Sir Francis Bacon',            'Knowledge is power.'),
  ('Socrates',                     'I cannot teach anybody anything. I can only make them think.'),
  ('Socrates',                     'The unexamined life is not worth living.'),
  ('Star Wars (many characters)',  'May the Force be with you.'),
  ('Stephen King',                 'Get busy living or get busy dying.'),
  ('Steve Jobs',                   'Design is not just what it looks like and feels like. Design is how it works.'),
  ('Steve Jobs',                   'Have the courage to follow your heart and intuition. They somehow already know what you truly want to become.'),
  ('Steve Jobs',                   'Innovation distinguishes between a leader and a follower.'),
  ('Steve Jobs',                   'I’m convinced that about half of what separates the successful entrepreneurs from the non-successful ones is pure perseverance.'),
  ('Steve Jobs',                   'My favorite things in life don’t cost any money. It’s really clear that the most precious resource we all have is time.'),
  ('Steve Jobs',                   'Quality is more important than quantity. One home run is much better than two doubles.'),
  ('Steve Jobs',                   'Stay hungry, stay foolish.'),
  ('Steve Jobs',                   'The only way to do great work is to love what you do.'),
  ('Steve Jobs',                   'The people who are crazy enough to think they can change the world are the ones who do.'),
  ('Steve Jobs',                   'Your time is limited, so don’t waste it living someone else’s life. Don’t be trapped by dogma - which is living with the results of other people’s thinking.'),
  ('Terminator (character)',       'I’ll be back.'),
  ('Theodore Roosevelt',           'Believe you can and you’re halfway there.'),
  ('Theodore Roosevelt',           'Do what you can, with what you have, where you are.'),
  ('Theodore Roosevelt',           'Speak softly and carry a big stick.'),
  ('Thomas Edison',                'Genius is one percent inspiration and ninety-nine percent perspiration.'),
  ('Thomas Jefferson',             'I find that the harder I work, the more luck I seem to have.'),
  ('Vito Corleone (character)',    'I’m gonna make him an offer he can’t refuse.'),
  ('Voltaire',                     'Appreciation is a wonderful thing. It makes what is excellent in others belong to us as well.'),
  ('Voltaire',                     'Cherish those who seek the truth but beware of those who find it.'),
  ('Voltaire',                     'Common sense is not so common.'),
  ('Voltaire',                     'Doubt is not a pleasant condition, but certainty is absurd.'),
  ('Voltaire',                     'Every man is guilty of all the good he did not do.'),
  ('Voltaire',                     'I disapprove of what you say, but I will defend to the death your right to say it.'),
  ('Voltaire',                     'It is dangerous to be right in matters on which the established authorities are wrong.'),
  ('Voltaire',                     'Judge a man by his questions rather than by his answers.'),
  ('Voltaire',                     'The more I read, the more I acquire, the more certain I am that I know nothing.'),
  ('Voltaire',                     'Those who can make you believe absurdities can make you commit atrocities.'),
  ('W. E. Hickson',                'If at first you don’t succeed, try, try again.'),
  ('Walt Disney',                  'The way to get started is to quit talking and begin doing.'),
  ('William Shakespeare',          'A rose by any other name would smell as sweet.'),
  ('William Shakespeare',          'All that glitters is not gold.'),
  ('William Shakespeare',          'All the world’s a stage, and all the men and women merely players.'),
  ('William Shakespeare',          'Parting is such sweet sorrow.'),
  ('William Shakespeare',          'To be or not to be, that is the question.'),
  ('William Shakespeare',          'To thine own self, be true.'),
  ('Winston Churchill',            'Attitude is a little thing that makes a big difference.'),
  ('Winston Churchill',            'Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.'),
  ('Winston Churchill',            'If you are going through hell, keep going.'),
  ('Winston Churchill',            'It is a mistake to look too far ahead. Only one link in the chain of destiny can be handled at a time.'),
  ('Winston Churchill',            'Never give in—never, never, never, never, in nothing great or small, large or petty, never give in except to convictions of honour and good sense.'),
  ('Winston Churchill',            'Success is not final, failure is not fatal: It is the courage to continue that counts.'),
  ('Winston Churchill',            'The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.'),
  ('Winston Churchill',            'To improve is to change; to be perfect is to change often.'),
  ('Winston Churchill',            'We make a living by what we get, but we make a life by what we give.'),
  ('Winston Churchill',            'You have enemies? Good. That means you’ve stood up for something, sometime in your life.'),
  ('Woody Allen',                  'Eighty percent of success is showing up.'),
  ('Yogi Berra',                   'It ain’t over till it’s over.'),
  ('Yogi Berra',                   'When you come to a fork in the road, take it.'),
  ('Yogi Berra',                   'You can observe a lot by just watching.'),
  ('Zig Ziglar',                   'People often say that motivation doesn’t last. Well, neither does bathing - that’s why we recommend it daily.'),
  ('Zig Ziglar',                   'You don’t have to be great to start, but you have to start to be great.');
